FROM ubuntu:20.04

ARG _ENV_NAME
ARG _DOMAIN
ARG _TIMEZONE
ARG _SERVER_PORT

ENV ENV_NAME=${_ENV_NAME}
ENV DOMAIN=${_DOMAIN}
ENV TZ=${_TIMEZONE}

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes

COPY ./docker/nodejs_18_setup.sh /home/nodejs_18_setup.sh

RUN cd ~ \
    # NodeJs
    && bash /home/nodejs_18_setup.sh \
    && apt-get update && apt-get install -y nodejs \
    # No root
    && groupadd -g 1000 node \
    && useradd -d /home/root/ -s /bin/bash -u 1000 -g 1000 node \
    && mkdir -p /home/root/ /usr/local/lib/node_modules/ \
    && chown -R node:node /home/root/ /usr/local/lib/node_modules/ /usr/local/bin/ \
    && chmod 775 /home/root/ /usr/local/lib/node_modules/ /usr/local/bin/ \
    # Apt
    && apt-get update && apt-get install -y \
    ca-certificates \
    # Certificate
    && update-ca-certificates \
    # Tls
    && mkdir -p /home/root/application/tls/certificate/ /var/log/ms_cronjob/tls/ \
    && chown -R node:node /home/root/application/tls/certificate/ /var/log/ms_cronjob/tls/ \
    && chmod 775 /home/root/application/tls/certificate/ /var/log/ms_cronjob/tls/ \
    # Clean
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean -y \
    && apt-get autoclean -y \
    && apt-get autoremove -y

USER node

WORKDIR /home/root/

# Tls
CMD chmod +x /home/root/application/tls/script/starter.sh \
    && bash /home/root/application/tls/script/starter.sh \
    # Keep running
    && tail -f /dev/null

EXPOSE ${_SERVER_PORT}
