FROM python:3.8

ARG _ENV_NAME
ARG _DOMAIN
ARG _TIMEZONE
ARG _SERVER_PORT
ARG _SERVER_LOCATION
ARG _PATH_ROOT

ENV ENV_NAME=${_ENV_NAME}
ENV DOMAIN=${_DOMAIN}
ENV TZ=${_TIMEZONE}
ENV SERVER_PORT=${_SERVER_PORT}
ENV SERVER_LOCATION=${_SERVER_LOCATION}
ENV PATH_ROOT=${_PATH_ROOT}

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes
ENV PATH="${PATH}:${PATH_ROOT}.local/bin/:/root/.local/bin/"
ENV PYTHONPATH="${PATH_ROOT}"
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV SUDO_FORCE_REMOVE=yes

COPY ./application/tls/certificate/proxy/ /usr/local/share/ca-certificates/

RUN cd ~ \
    && VERSION_CODENAME=$(grep VERSION_CODENAME= /etc/os-release | cut -d= -f2) \
    && chmod -R 0644 /usr/local/share/ca-certificates/ \
    && apt-get update && apt-get install -y ca-certificates gnupg curl \
    && update-ca-certificates \
    # No root
    && groupadd -g 1000 pyuser \
    && useradd -d ${PATH_ROOT} -s /bin/bash -u 1000 -g 1000 pyuser \
    && mkdir -p ${PATH_ROOT} ${PATH_ROOT}file_share/certificate/ \
    && chown -R pyuser:pyuser ${PATH_ROOT} \
    && chmod -R 775 ${PATH_ROOT} \
    # Apt
    && apt-get update && apt-get install -y \
    fonts-noto \
    fonts-noto-cjk \
    postgresql-client \
    # Clean
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean -y \
    && apt-get autoclean -y \
    && apt-get autoremove -y

USER pyuser

WORKDIR ${PATH_ROOT}

# Tls
CMD chmod +x ${PATH_ROOT}application/tls/script/starter.sh \
    && bash ${PATH_ROOT}application/tls/script/starter.sh \
    && find ${PATH_ROOT}application/tls/certificate/ -maxdepth 1 -type f -exec cp {} ${PATH_ROOT}file_share/certificate/ \; \
    # Pip
    && python3 -m pip install pip --upgrade \
    && python3 -m pip install --user --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org -r ${PATH_ROOT}application/requirements.txt \
    # Cron
    && yacron -c ${PATH_ROOT}cronjob.yaml -v \
    && yacron -c ${PATH_ROOT}cronjob.yaml \
    # Keep running
    && tail -f /dev/null

EXPOSE ${SERVER_PORT}
